name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - renovate/**
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install js dependencies
        run: bun install
      - name: Run cargo test
        run: cargo test --verbose
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install js dependencies
        run: bun install
      - name: Run cargo build
        run: cargo build --verbose
  clippy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install js dependencies
        run: bun install
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
  fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
  sqlx-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DATABASE_URL: sqlite:./db.sqlite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install js dependencies
        run: bun install
      - name: Install sqlx-cli
        run: cargo install sqlx-cli
      - name: Create sqlite database
        run: touch db.sqlite
      - name: Run migrations
        run: sqlx migrate run
      - name: Check sqlx directory
        run: cargo sqlx prepare --check